spring.application.name=TriviaGenerator

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update



security.jwt.secret-key=XyvcZkxhcxUmp4tCsaMaDFdsZfTfI0i1LyNbwAm5fMw=
security.jwt.expiration=86400000