spring.application.name=TriviaGenerator

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${POSTGRES_URL}

spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG

security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration=86400000